<div class="row">
    <div class="col-12 py-5 text-center">
        <h1>
            CodePen Challenge - InsanityMeetsHH
            <a href="https://github.com/InsanityMeetsHH/codepen-challenge" target="_blank"><i class="fab fa-inverse fa-github" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="GitHub"></i></a>
        </h1>
    </div>
</div>
<div class="row text-center justify-content-center pb-5">
    <div class="col-12 d-none">
        <span style="font-size: 1.75rem;"><?php echo $lang['included']; ?></span>
    </div>
    <div class="col-12">
        <nav>
            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <a class="nav-item nav-link active" id="nav-cpc-sandwich-tab" data-toggle="tab" href="#nav-cpc-sandwich" role="tab" aria-controls="nav-cpc-sandwich" aria-selected="true">Sandwich</a>
            </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active pt-4" id="nav-cpc-sandwich" role="tabpanel" aria-labelledby="nav-cpc-sandwich-tab">
                <div class="cpc-sandwich cpc-ratio-16by9">
                    <input type="checkbox" id="sandwich-done" style="display: none;" />
                    <input type="checkbox" id="sandwich-tomatoes" style="display: none;" />
                    <input type="checkbox" id="sandwich-bacons" style="display: none;" />
                    <input type="checkbox" id="sandwich-lettuces" style="display: none;" />
                    <input type="checkbox" id="sandwich-cheese" style="display: none;" />

                    <div class="bowl bowl-1"></div>
                    <div class="bowl bowl-2"></div>
                    <div class="bowl bowl-3"></div>
                    <div class="bowl bowl-4"></div>
                    <div class="board"></div>

                    <div class="sticker">
                        <div></div>
                        <div></div>
                        <div></div>
                        <div></div>
                        <div class="overlay"></div>
                        <div class="overlay"></div>
                        <div class="overlay"></div>
                        <div class="overlay"></div>
                    </div>

                    <div class="bread bread-1"></div>

                    <label class="lettuces" for="sandwich-lettuces">
                        <div class="lettuce lettuce-1"></div>
                        <div class="lettuce lettuce-2"></div>
                        <div class="lettuce lettuce-3"></div>
                        <div class="lettuce lettuce-4"></div>
                        <div class="lettuce lettuce-5"></div>
                        <div class="lettuce lettuce-6"></div>
                        <div class="lettuce lettuce-7"></div>
                        <div class="lettuce lettuce-8"></div>
                        <div class="lettuce lettuce-9"></div>
                        <div class="lettuce lettuce-10"></div>
                    </label>

                    <label class="bacons" for="sandwich-bacons">
                        <div class="bacon bacon-1"></div>
                        <div class="bacon bacon-2"></div>
                        <div class="bacon bacon-3"></div>
                        <div class="bacon bacon-4"></div>
                    </label>

                    <label class="tomatoes" for="sandwich-tomatoes">
                        <div class="tomato tomato-1"></div>
                        <div class="tomato tomato-2"></div>
                        <div class="tomato tomato-3"></div>
                        <div class="tomato tomato-4"></div>
                        <div class="tomato tomato-5"></div>
                        <div class="tomato tomato-6"></div>
                    </label>

                    <label class="cheese" for="sandwich-cheese">
                        <div class="slice slice-1"></div>
                        <div class="slice slice-2"></div>
                    </label>

                    <div class="bread bread-2"></div>

                    <div class="disrupter"></div>

                    <label class="done" for="sandwich-done">
                        <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="check" class="svg-inline--fa fa-check fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M173.898 439.404l-166.4-166.4c-9.997-9.997-9.997-26.206 0-36.204l36.203-36.204c9.997-9.998 26.207-9.998 36.204 0L192 312.69 432.095 72.596c9.997-9.997 26.207-9.997 36.204 0l36.203 36.204c9.997 9.997 9.997 26.206 0 36.204l-294.4 294.401c-9.998 9.997-26.207 9.997-36.204-.001z"></path></svg>
                        <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="times" class="svg-inline--fa fa-times fa-w-11" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 352 512"><path fill="currentColor" d="M242.72 256l100.07-100.07c12.28-12.28 12.28-32.19 0-44.48l-22.24-22.24c-12.28-12.28-32.19-12.28-44.48 0L176 189.28 75.93 89.21c-12.28-12.28-32.19-12.28-44.48 0L9.21 111.45c-12.28 12.28-12.28 32.19 0 44.48L109.28 256 9.21 356.07c-12.28 12.28-12.28 32.19 0 44.48l22.24 22.24c12.28 12.28 32.2 12.28 44.48 0L176 322.72l100.07 100.07c12.28 12.28 32.2 12.28 44.48 0l22.24-22.24c12.28-12.28 12.28-32.19 0-44.48L242.72 256z"></path></svg>
                    </label>
                </div>
            </div>
        </div>
    </div>
</div>
